drop procedure update_customer_tier;
drop table customer_activity purge;
drop table customer_redeem_activity purge;
drop table customer_lp_enroll purge;
drop table wallet purge;
drop table customer purge;
drop table activities_for_loyalty_program purge;
drop table rewards_for_loyalty_program purge;
drop table rr_rule_for_lp purge;
drop table rr_rule purge;
drop table re_rule_for_lp purge;
drop table re_rule purge;
drop table tier purge;
drop table loyalty_program purge;
drop table brand purge;
drop table reward_category purge;
drop table activity_category purge;
drop table actor purge;
